version: '3.8'
services:
  hello_world:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: dev
      SYMFONY_DEPRECATIONS_HELPER: weak
    command: bash -c "composer install && php-fpm"
